@startuml
title Communication Scheme
database "Backend" as layer
participant "Player Host Application" as app
layer -> app: load player code

create Player
app -> Player: load player code
Player -> app: notify "ready"

loop Set Unit 0..unbound
    layer -> app: load unit definition
    layer -> app: load unit state
    app -> Player: command "start"

    loop Player User Interaction 0..unbound
        alt
            Player -> app: changed state
            app -> layer: Store new state
        else
            Player -> app: request unit navigation
        else
            app -> Player: command "page navigation"
        else
            app -> Player: notify "Navigation Denied"
        else
            Player -> layer: request content
            layer -> Player: load content
        else
            Player -> app: notify "Window Focus Changed"
        end
    end
end
app -> Player: (destroy)
destroy Player

@enduml
