@startuml
title Communication between Player and Application
participant "Player Host Application" as app

create Player
app -> Player: (load)
Player -> app: ReadyNotification

group Start Command
    app --> Player: SetUnitDefinitionCommand
    app --> Player: SetPlayerConfigCommand
    app --> Player: SetPreviousUnitStateCommand

    app -> Player: StartCommand
end

loop Player User Interaction 0..unbound
    alt
        Player -> app: UnitStateChangedNotification
    else
        app -> Player: PageNavigationCommand
    else
        app -> Player: StopCommand
    else
        app -> Player: ContinueCommand
    end
end

Player --> app: UnitNavigationRequestedNotification
app --> Player: GetUnitStateRequest
Player --> app: GetUnitStateResponse

app -> Player: (destroy)
destroy Player

@enduml
