@startuml
title Use Case 4: Unit State Evaluation
database "Persistence Layer" as layer
participant "Player Host Application" as app
actor User order 4
User -> app: Coding Job Selection

loop per Unit
    create Player
    app -> Player: (create)
    loop per Testee
        layer-> app: Previous Unit State
        app -> Player: Previous Unit State
        app -> Player: Start Unit
        User -[#red]> Player: <font color=red>Evaluate Unit State</font>
        Player -[#red]> app: <font color=red>Unit State Evaluation</font>
        app -[#red]> layer: <font color=red>Unit State Evaluation</font>
        User -[#red]> app: <font color=red>Testee Navigation Request</font>
    end

    User -> app: Unit Navigation Request
    app -> Player: (destroy)
    destroy Player
end

@enduml
